### PR TITLE
Add HDMI audio HAL on external sound

### PR DESCRIPTION
**Pull request by kkm123**
Add HDMI audio HAL on external sound

Adding Intel customized HDMI Audio HAL to sound repo

Tracked-On: OAM-84728
Signed-off-by: M, Kumar K <kumar.k.m@intel.com>

### CODE REVIEW

**Review by karanpat — APPROVED** [review]
Adding Intel customized HDMI Audio HAL to sound repo.
Looks good. Please apply the changes.

**Comment by chenlin3** [comment]
Please only keep short OAM info in Tracked-on section

**Comment by kkm123** [comment]
Updated PR with short OAM info

**Review by karanpat — APPROVED** [review]
Looks good. Please submit.

**Pull request merged**
